---
title: ''
author: "andrés castro araújo"
date: '2022-06-21'
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

The phrase "correlation is NOT causality" has become part of popular culture. 

Suppose you've found a pattern or an association between two variables $X$ and $Y$. This could mean any of the following:

1.    Variable $X$ causes variable $Y$ (or maybe it's the other way around).
2.    Both variables are unrelated and the association is an artifact of random sampling.
3.    The association is is due to a third unobserved variable (also known as a confounder).
4.    The association is an artifact of the way the data is selected. This also known as "conditioning on common effects" or "collider bias." The important question to ask here is "Who or what gets excluded from our sample?" (e.g., [here](https://fivethirtyeight.com/features/why-statistics-dont-capture-the-full-extent-of-the-systemic-bias-in-policing/)). 
    A much more advanced introduction to this topic is given by [Elwert & Winship (2014)](https://www.annualreviews.org/doi/abs/10.1146/annurev-soc-071913-043455).

There are many places to learn about causality.

-   Introductory textbooks like [_Quantitative Social Science_](https://press.princeton.edu/books/paperback/9780691175461/quantitative-social-science) (Imai 2018), [_Thinking Clearly With Data_](https://press.princeton.edu/books/hardcover/9780691214368/thinking-clearly-with-data) (de Mesquita & Fowler 2021), or [_The Effect_](https://theeffectbook.net/) (Huntington-Klein, 2022).

-   Miguel Hernan's online course on [_Causal Diagrams_](https://www.edx.org/course/causal-diagrams-draw-your-assumptions-before-your).

-   Etc.
